services:
  windows:
    image: dockurr/windows
    container_name: Win11
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: 4
      DISK_SIZE: "100G"
      USERNAME: "Tayyab"
      PASSWORD: "password"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ./data:/storage
