version: '3.8'

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  cloudflared:
    container_name: Ranchwood-CloudFlareTunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=token0key
    command: tunnel --no-autoupdate run
    networks:
      - frontend
      - backend

