---
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - FIREFOX_CLI=https://www.google.com/ #optional
      - CUSTOM_USER=Tayyab
      - PASSWORD=#yourpassword
    volumes:
      - ./data:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped

